import { db } from '@/db';
import { auditLogs } from '@/db/schema';

async function main() {
    const sampleAuditLogs = [
        // CREATE actions (15 logs)
        {
            userId: 2,
            action: 'CREATE',
            entityType: 'trial_report',
            entityId: 1,
            oldValue: null,
            newValue: { status: 'pending', totalDebits: 5000000, totalCredits: 5000000, reportingPeriod: '2024-03', reportType: 'monthly' },
            ipAddress: '192.168.1.45',
            timestamp: new Date('2024-03-15T09:15:00Z').toISOString(),
        },
        {
            userId: 4,
            action: 'CREATE',
            entityType: 'trial_report',
            entityId: 2,
            oldValue: null,
            newValue: { status: 'pending', totalDebits: 8500000, totalCredits: 8500000, reportingPeriod: '2024-03', reportType: 'monthly' },
            ipAddress: '192.168.1.67',
            timestamp: new Date('2024-03-16T10:30:00Z').toISOString(),
        },
        {
            userId: 6,
            action: 'CREATE',
            entityType: 'entity',
            entityId: 35,
            oldValue: null,
            newValue: { name: 'Lagos Regional Office', code: 'LRO-001', department: 'Operations', region: 'West Africa', status: 'active' },
            ipAddress: '10.0.0.23',
            timestamp: new Date('2024-03-18T14:20:00Z').toISOString(),
        },
        {
            userId: 1,
            action: 'CREATE',
            entityType: 'assignment',
            entityId: 45,
            oldValue: null,
            newValue: { entityId: 12, stakeholderId: 9, roleType: 'reviewer', status: 'pending', dueDate: '2024-04-15' },
            ipAddress: '192.168.1.89',
            timestamp: new Date('2024-03-20T08:45:00Z').toISOString(),
        },
        {
            userId: 3,
            action: 'CREATE',
            entityType: 'trial_report',
            entityId: 3,
            oldValue: null,
            newValue: { status: 'pending', totalDebits: 12000000, totalCredits: 12000000, reportingPeriod: '2024-04', reportType: 'monthly' },
            ipAddress: '172.16.0.15',
            timestamp: new Date('2024-04-05T11:00:00Z').toISOString(),
        },
        {
            userId: 5,
            action: 'CREATE',
            entityType: 'gl_account',
            entityId: 120,
            oldValue: null,
            newValue: { accountNumber: '1100-001', accountName: 'Cash and Bank', accountType: 'asset', currentBalance: 2500000, currency: 'USD' },
            ipAddress: '192.168.1.101',
            timestamp: new Date('2024-04-08T09:30:00Z').toISOString(),
        },
        {
            userId: 7,
            action: 'CREATE',
            entityType: 'assignment',
            entityId: 46,
            oldValue: null,
            newValue: { entityId: 18, stakeholderId: 11, roleType: 'checker', status: 'pending', dueDate: '2024-04-20' },
            ipAddress: '10.0.0.45',
            timestamp: new Date('2024-04-10T13:15:00Z').toISOString(),
        },
        {
            userId: 8,
            action: 'CREATE',
            entityType: 'trial_report',
            entityId: 4,
            oldValue: null,
            newValue: { status: 'pending', totalDebits: 6750000, totalCredits: 6750000, reportingPeriod: '2024-04', reportType: 'monthly' },
            ipAddress: '192.168.1.112',
            timestamp: new Date('2024-04-12T10:45:00Z').toISOString(),
        },
        {
            userId: 2,
            action: 'CREATE',
            entityType: 'entity',
            entityId: 36,
            oldValue: null,
            newValue: { name: 'Abuja Branch', code: 'ABJ-002', department: 'Finance', region: 'Central', status: 'active' },
            ipAddress: '172.16.0.28',
            timestamp: new Date('2024-04-15T14:30:00Z').toISOString(),
        },
        {
            userId: 4,
            action: 'CREATE',
            entityType: 'assignment',
            entityId: 47,
            oldValue: null,
            newValue: { entityId: 25, stakeholderId: 13, roleType: 'maker', status: 'pending', dueDate: '2024-05-01' },
            ipAddress: '192.168.1.134',
            timestamp: new Date('2024-04-18T08:20:00Z').toISOString(),
        },
        {
            userId: 6,
            action: 'CREATE',
            entityType: 'stakeholder',
            entityId: 19,
            oldValue: null,
            newValue: { name: 'Amara Okafor', email: 'amara.okafor@company.com', role: 'maker', department: 'Finance' },
            ipAddress: '10.0.0.67',
            timestamp: new Date('2024-04-22T11:40:00Z').toISOString(),
        },
        {
            userId: 1,
            action: 'CREATE',
            entityType: 'trial_report',
            entityId: 5,
            oldValue: null,
            newValue: { status: 'pending', totalDebits: 9200000, totalCredits: 9200000, reportingPeriod: '2024-05', reportType: 'monthly' },
            ipAddress: '192.168.1.145',
            timestamp: new Date('2024-05-03T09:10:00Z').toISOString(),
        },
        {
            userId: 3,
            action: 'CREATE',
            entityType: 'gl_account',
            entityId: 121,
            oldValue: null,
            newValue: { accountNumber: '2100-001', accountName: 'Accounts Payable', accountType: 'liability', currentBalance: 1800000, currency: 'USD' },
            ipAddress: '172.16.0.39',
            timestamp: new Date('2024-05-07T10:25:00Z').toISOString(),
        },
        {
            userId: 5,
            action: 'CREATE',
            entityType: 'assignment',
            entityId: 48,
            oldValue: null,
            newValue: { entityId: 30, stakeholderId: 10, roleType: 'reviewer', status: 'pending', dueDate: '2024-05-15' },
            ipAddress: '192.168.1.156',
            timestamp: new Date('2024-05-10T13:50:00Z').toISOString(),
        },
        {
            userId: 7,
            action: 'CREATE',
            entityType: 'trial_report',
            entityId: 6,
            oldValue: null,
            newValue: { status: 'pending', totalDebits: 7800000, totalCredits: 7800000, reportingPeriod: '2024-05', reportType: 'monthly' },
            ipAddress: '10.0.0.89',
            timestamp: new Date('2024-05-14T08:35:00Z').toISOString(),
        },

        // UPDATE actions (20 logs)
        {
            userId: 9,
            action: 'UPDATE',
            entityType: 'trial_report',
            entityId: 1,
            oldValue: { status: 'pending', reviewedBy: null },
            newValue: { status: 'in_review', reviewedBy: 9, reviewedAt: '2024-03-16T10:00:00Z' },
            ipAddress: '192.168.1.201',
            timestamp: new Date('2024-03-16T10:00:00Z').toISOString(),
        },
        {
            userId: 11,
            action: 'UPDATE',
            entityType: 'gl_account',
            entityId: 45,
            oldValue: { currentBalance: 1500000, previousBalance: 1450000 },
            newValue: { currentBalance: 1550000, previousBalance: 1500000 },
            ipAddress: '10.0.0.112',
            timestamp: new Date('2024-03-19T11:20:00Z').toISOString(),
        },
        {
            userId: 10,
            action: 'UPDATE',
            entityType: 'assignment',
            entityId: 45,
            oldValue: { status: 'pending', completedAt: null },
            newValue: { status: 'in_progress', completedAt: null },
            ipAddress: '172.16.0.56',
            timestamp: new Date('2024-03-21T09:15:00Z').toISOString(),
        },
        {
            userId: 13,
            action: 'UPDATE',
            entityType: 'trial_report',
            entityId: 2,
            oldValue: { status: 'pending', totalDebits: 8500000, totalCredits: 8500000 },
            newValue: { status: 'in_review', totalDebits: 8500000, totalCredits: 8500000, reviewedBy: 13 },
            ipAddress: '192.168.1.223',
            timestamp: new Date('2024-03-22T14:30:00Z').toISOString(),
        },
        {
            userId: 12,
            action: 'UPDATE',
            entityType: 'entity',
            entityId: 15,
            oldValue: { status: 'active', department: 'Operations' },
            newValue: { status: 'active', department: 'Finance' },
            ipAddress: '10.0.0.134',
            timestamp: new Date('2024-03-25T10:45:00Z').toISOString(),
        },
        {
            userId: 9,
            action: 'UPDATE',
            entityType: 'gl_account',
            entityId: 67,
            oldValue: { currentBalance: 3200000, previousBalance: 3100000 },
            newValue: { currentBalance: 3350000, previousBalance: 3200000 },
            ipAddress: '192.168.1.245',
            timestamp: new Date('2024-04-02T08:50:00Z').toISOString(),
        },
        {
            userId: 14,
            action: 'UPDATE',
            entityType: 'assignment',
            entityId: 46,
            oldValue: { status: 'pending' },
            newValue: { status: 'completed', completedAt: '2024-04-11T15:20:00Z' },
            ipAddress: '172.16.0.78',
            timestamp: new Date('2024-04-11T15:20:00Z').toISOString(),
        },
        {
            userId: 11,
            action: 'UPDATE',
            entityType: 'trial_report',
            entityId: 3,
            oldValue: { status: 'pending', balanceDifference: 0 },
            newValue: { status: 'in_review', balanceDifference: 0, reviewedBy: 11 },
            ipAddress: '10.0.0.156',
            timestamp: new Date('2024-04-13T11:10:00Z').toISOString(),
        },
        {
            userId: 10,
            action: 'UPDATE',
            entityType: 'stakeholder',
            entityId: 8,
            oldValue: { department: 'Operations', role: 'maker' },
            newValue: { department: 'Finance', role: 'maker' },
            ipAddress: '192.168.1.267',
            timestamp: new Date('2024-04-16T09:35:00Z').toISOString(),
        },
        {
            userId: 13,
            action: 'UPDATE',
            entityType: 'gl_account',
            entityId: 89,
            oldValue: { currentBalance: 5600000, previousBalance: 5450000 },
            newValue: { currentBalance: 5750000, previousBalance: 5600000 },
            ipAddress: '172.16.0.91',
            timestamp: new Date('2024-04-19T14:15:00Z').toISOString(),
        },
        {
            userId: 12,
            action: 'UPDATE',
            entityType: 'trial_report',
            entityId: 4,
            oldValue: { status: 'pending', reviewedBy: null },
            newValue: { status: 'in_review', reviewedBy: 12, reviewedAt: '2024-04-20T10:25:00Z' },
            ipAddress: '10.0.0.178',
            timestamp: new Date('2024-04-20T10:25:00Z').toISOString(),
        },
        {
            userId: 9,
            action: 'UPDATE',
            entityType: 'assignment',
            entityId: 47,
            oldValue: { status: 'pending', dueDate: '2024-05-01' },
            newValue: { status: 'in_progress', dueDate: '2024-05-01' },
            ipAddress: '192.168.1.289',
            timestamp: new Date('2024-04-23T08:40:00Z').toISOString(),
        },
        {
            userId: 14,
            action: 'UPDATE',
            entityType: 'entity',
            entityId: 36,
            oldValue: { region: 'Central', status: 'active' },
            newValue: { region: 'North Central', status: 'active' },
            ipAddress: '172.16.0.103',
            timestamp: new Date('2024-04-26T13:55:00Z').toISOString(),
        },
        {
            userId: 11,
            action: 'UPDATE',
            entityType: 'gl_account',
            entityId: 120,
            oldValue: { currentBalance: 2500000, previousBalance: 2400000 },
            newValue: { currentBalance: 2650000, previousBalance: 2500000 },
            ipAddress: '10.0.0.190',
            timestamp: new Date('2024-05-01T09:20:00Z').toISOString(),
        },
        {
            userId: 10,
            action: 'UPDATE',
            entityType: 'trial_report',
            entityId: 5,
            oldValue: { status: 'pending', totalDebits: 9200000 },
            newValue: { status: 'in_review', totalDebits: 9200000, reviewedBy: 10 },
            ipAddress: '192.168.1.301',
            timestamp: new Date('2024-05-05T11:45:00Z').toISOString(),
        },
        {
            userId: 13,
            action: 'UPDATE',
            entityType: 'assignment',
            entityId: 48,
            oldValue: { status: 'pending', completedAt: null },
            newValue: { status: 'completed', completedAt: '2024-05-12T16:30:00Z' },
            ipAddress: '172.16.0.125',
            timestamp: new Date('2024-05-12T16:30:00Z').toISOString(),
        },
        {
            userId: 12,
            action: 'UPDATE',
            entityType: 'gl_account',
            entityId: 121,
            oldValue: { currentBalance: 1800000, previousBalance: 1750000 },
            newValue: { currentBalance: 1920000, previousBalance: 1800000 },
            ipAddress: '10.0.0.201',
            timestamp: new Date('2024-05-15T10:15:00Z').toISOString(),
        },
        {
            userId: 9,
            action: 'UPDATE',
            entityType: 'trial_report',
            entityId: 6,
            oldValue: { status: 'pending', balanceDifference: 0 },
            newValue: { status: 'in_review', balanceDifference: 0, reviewedBy: 9, reviewedAt: '2024-05-16T14:20:00Z' },
            ipAddress: '192.168.1.323',
            timestamp: new Date('2024-05-16T14:20:00Z').toISOString(),
        },
        {
            userId: 14,
            action: 'UPDATE',
            entityType: 'stakeholder',
            entityId: 19,
            oldValue: { department: 'Finance', notificationPreferences: { email: true, sms: false } },
            newValue: { department: 'Finance', notificationPreferences: { email: true, sms: true } },
            ipAddress: '172.16.0.147',
            timestamp: new Date('2024-05-20T09:50:00Z').toISOString(),
        },
        {
            userId: 11,
            action: 'UPDATE',
            entityType: 'assignment',
            entityId: 52,
            oldValue: { status: 'in_progress', dueDate: '2024-05-25' },
            newValue: { status: 'completed', dueDate: '2024-05-25', completedAt: '2024-05-22T13:40:00Z' },
            ipAddress: '10.0.0.223',
            timestamp: new Date('2024-05-22T13:40:00Z').toISOString(),
        },

        // DELETE actions (5 logs)
        {
            userId: 15,
            action: 'DELETE',
            entityType: 'assignment',
            entityId: 32,
            oldValue: { entityId: 8, stakeholderId: 5, roleType: 'reviewer', status: 'obsolete' },
            newValue: null,
            ipAddress: '192.168.1.345',
            timestamp: new Date('2024-04-01T10:30:00Z').toISOString(),
        },
        {
            userId: 16,
            action: 'DELETE',
            entityType: 'gl_account',
            entityId: 98,
            oldValue: { accountNumber: '9999-999', accountName: 'Obsolete Account', accountType: 'expense', status: 'inactive' },
            newValue: null,
            ipAddress: '10.0.0.245',
            timestamp: new Date('2024-04-12T14:15:00Z').toISOString(),
        },
        {
            userId: 17,
            action: 'DELETE',
            entityType: 'stakeholder',
            entityId: 14,
            oldValue: { name: 'Former Employee', email: 'former@company.com', role: 'maker', status: 'inactive' },
            newValue: null,
            ipAddress: '172.16.0.169',
            timestamp: new Date('2024-04-25T11:20:00Z').toISOString(),
        },
        {
            userId: 15,
            action: 'DELETE',
            entityType: 'trial_report',
            entityId: 28,
            oldValue: { status: 'draft', totalDebits: 0, totalCredits: 0, reportingPeriod: '2023-12' },
            newValue: null,
            ipAddress: '192.168.1.367',
            timestamp: new Date('2024-05-08T09:45:00Z').toISOString(),
        },
        {
            userId: 16,
            action: 'DELETE',
            entityType: 'entity',
            entityId: 42,
            oldValue: { name: 'Closed Branch', code: 'CLB-001', status: 'inactive', region: 'South' },
            newValue: null,
            ipAddress: '10.0.0.267',
            timestamp: new Date('2024-05-18T15:30:00Z').toISOString(),
        },

        // APPROVE actions (7 logs)
        {
            userId: 15,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 1,
            oldValue: { status: 'in_review', balanceDifference: 0 },
            newValue: { status: 'approved', approvedBy: 15, approvedAt: '2024-03-17T11:30:00Z' },
            ipAddress: '192.168.1.389',
            timestamp: new Date('2024-03-17T11:30:00Z').toISOString(),
        },
        {
            userId: 16,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 2,
            oldValue: { status: 'in_review', reviewedBy: 13 },
            newValue: { status: 'approved', approvedBy: 16, approvedAt: '2024-03-23T15:45:00Z' },
            ipAddress: '10.0.0.289',
            timestamp: new Date('2024-03-23T15:45:00Z').toISOString(),
        },
        {
            userId: 17,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 3,
            oldValue: { status: 'in_review', balanceDifference: 0, reviewedBy: 11 },
            newValue: { status: 'approved', approvedBy: 17, approvedAt: '2024-04-14T10:20:00Z' },
            ipAddress: '172.16.0.191',
            timestamp: new Date('2024-04-14T10:20:00Z').toISOString(),
        },
        {
            userId: 15,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 4,
            oldValue: { status: 'in_review', reviewedBy: 12 },
            newValue: { status: 'approved', approvedBy: 15, approvedAt: '2024-04-21T13:10:00Z' },
            ipAddress: '192.168.1.401',
            timestamp: new Date('2024-04-21T13:10:00Z').toISOString(),
        },
        {
            userId: 16,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 7,
            oldValue: { status: 'in_review', balanceDifference: 500 },
            newValue: { status: 'approved', approvedBy: 16, approvedAt: '2024-05-02T09:35:00Z', approvalNote: 'Minor variance within tolerance' },
            ipAddress: '10.0.0.301',
            timestamp: new Date('2024-05-02T09:35:00Z').toISOString(),
        },
        {
            userId: 17,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 5,
            oldValue: { status: 'in_review', reviewedBy: 10, balanceDifference: 0 },
            newValue: { status: 'approved', approvedBy: 17, approvedAt: '2024-05-06T14:50:00Z' },
            ipAddress: '172.16.0.213',
            timestamp: new Date('2024-05-06T14:50:00Z').toISOString(),
        },
        {
            userId: 18,
            action: 'APPROVE',
            entityType: 'trial_report',
            entityId: 6,
            oldValue: { status: 'in_review', reviewedBy: 9 },
            newValue: { status: 'approved', approvedBy: 18, approvedAt: '2024-05-17T11:15:00Z' },
            ipAddress: '192.168.1.423',
            timestamp: new Date('2024-05-17T11:15:00Z').toISOString(),
        },

        // REJECT actions (3 logs)
        {
            userId: 15,
            action: 'REJECT',
            entityType: 'trial_report',
            entityId: 15,
            oldValue: { status: 'in_review', balanceDifference: 25000, reviewedBy: 12 },
            newValue: { status: 'rejected', rejectionReason: 'Balance mismatch exceeds tolerance', rejectedBy: 15, rejectedAt: '2024-04-05T16:20:00Z' },
            ipAddress: '10.0.0.323',
            timestamp: new Date('2024-04-05T16:20:00Z').toISOString(),
        },
        {
            userId: 16,
            action: 'REJECT',
            entityType: 'trial_report',
            entityId: 18,
            oldValue: { status: 'in_review', totalDebits: 4500000, totalCredits: 4580000 },
            newValue: { status: 'rejected', rejectionReason: 'Significant discrepancy in totals requiring investigation', rejectedBy: 16, rejectedAt: '2024-04-28T10:40:00Z' },
            ipAddress: '172.16.0.235',
            timestamp: new Date('2024-04-28T10:40:00Z').toISOString(),
        },
        {
            userId: 17,
            action: 'REJECT',
            entityType: 'trial_report',
            entityId: 22,
            oldValue: { status: 'in_review', balanceDifference: 45000, reviewedBy: 11 },
            newValue: { status: 'rejected', rejectionReason: 'Multiple account balance discrepancies detected', rejectedBy: 17, rejectedAt: '2024-05-11T15:55:00Z' },
            ipAddress: '192.168.1.445',
            timestamp: new Date('2024-05-11T15:55:00Z').toISOString(),
        },
    ];

    await db.insert(auditLogs).values(sampleAuditLogs);
    
    console.log('✅ Audit logs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});