import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const sampleNotifications = [
        // Reminders for stakeholders 1-6 (Makers) - Recent unread
        {
            stakeholderId: 2,
            message: 'Reminder: Trial report for Global Manufacturing Ltd is due in 3 days',
            type: 'reminder',
            readStatus: false,
            sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 3,
            relatedReportId: null,
        },
        {
            stakeholderId: 4,
            message: 'Upcoming deadline: Submit trial balance for Q1 2024',
            type: 'reminder',
            readStatus: false,
            sentAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 5,
            relatedReportId: null,
        },
        {
            stakeholderId: 1,
            message: 'Overdue: Trial report submission for TechCorp Industries',
            type: 'reminder',
            readStatus: false,
            sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 1,
            relatedReportId: null,
        },
        {
            stakeholderId: 5,
            message: 'Reminder: Trial report for Retail Solutions Inc is due in 5 days',
            type: 'reminder',
            readStatus: false,
            sentAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 7,
            relatedReportId: null,
        },
        // Reminders - Older read
        {
            stakeholderId: 3,
            message: 'Upcoming deadline: Submit trial balance for December 2023',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 2,
            relatedReportId: null,
        },
        {
            stakeholderId: 6,
            message: 'Reminder: Trial report for Healthcare Services Co is due in 2 days',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 8,
            relatedReportId: null,
        },
        {
            stakeholderId: 2,
            message: 'Overdue: Trial report submission for Financial Group LLC',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 4,
            relatedReportId: null,
        },
        {
            stakeholderId: 4,
            message: 'Upcoming deadline: Submit trial balance for Q4 2023',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 6,
            relatedReportId: null,
        },
        {
            stakeholderId: 1,
            message: 'Reminder: Trial report for Energy Solutions Ltd is due in 7 days',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 9,
            relatedReportId: null,
        },
        {
            stakeholderId: 5,
            message: 'Overdue: Trial report submission for Construction Corp',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 27 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 10,
            relatedReportId: null,
        },
        {
            stakeholderId: 3,
            message: 'Upcoming deadline: Submit trial balance for November 2023',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 1,
            relatedReportId: null,
        },
        {
            stakeholderId: 6,
            message: 'Reminder: Trial report for Global Manufacturing Ltd is due in 4 days',
            type: 'reminder',
            readStatus: true,
            sentAt: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 3,
            relatedReportId: null,
        },
        // Alerts for stakeholders 1-12 (Makers and Checkers) - Recent unread
        {
            stakeholderId: 7,
            message: 'Alert: Trial balance out of balance by $15,234.50',
            type: 'alert',
            readStatus: false,
            sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 2,
            relatedReportId: 5,
        },
        {
            stakeholderId: 9,
            message: 'Variance anomaly detected for TechCorp Industries - Q1 2024',
            type: 'alert',
            readStatus: false,
            sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 1,
            relatedReportId: 8,
        },
        {
            stakeholderId: 3,
            message: 'Critical: Large balance difference requires attention',
            type: 'alert',
            readStatus: false,
            sentAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 4,
            relatedReportId: 12,
        },
        {
            stakeholderId: 11,
            message: 'Alert: Trial balance out of balance by $8,967.25',
            type: 'alert',
            readStatus: false,
            sentAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 6,
            relatedReportId: 15,
        },
        // Alerts - Older read
        {
            stakeholderId: 8,
            message: 'Variance anomaly detected for Retail Solutions Inc - December 2023',
            type: 'alert',
            readStatus: true,
            sentAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 7,
            relatedReportId: 18,
        },
        {
            stakeholderId: 10,
            message: 'Alert: Trial balance out of balance by $22,145.80',
            type: 'alert',
            readStatus: true,
            sentAt: new Date(Date.now() - 16 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 8,
            relatedReportId: 20,
        },
        {
            stakeholderId: 12,
            message: 'Critical: Large balance difference requires attention',
            type: 'alert',
            readStatus: true,
            sentAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 9,
            relatedReportId: 22,
        },
        {
            stakeholderId: 2,
            message: 'Variance anomaly detected for Energy Solutions Ltd - Q4 2023',
            type: 'alert',
            readStatus: true,
            sentAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 9,
            relatedReportId: 24,
        },
        {
            stakeholderId: 7,
            message: 'Alert: Trial balance out of balance by $5,432.15',
            type: 'alert',
            readStatus: true,
            sentAt: new Date(Date.now() - 23 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 10,
            relatedReportId: 26,
        },
        {
            stakeholderId: 4,
            message: 'Critical: Large balance difference requires attention',
            type: 'alert',
            readStatus: true,
            sentAt: new Date(Date.now() - 26 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 3,
            relatedReportId: 28,
        },
        // Approval requests for stakeholders 7-18 (Checkers and Approvers) - Unread
        {
            stakeholderId: 13,
            message: 'Approval needed: Trial report for TechCorp Industries - Q1 2024',
            type: 'approval_request',
            readStatus: false,
            sentAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 1,
            relatedReportId: 3,
        },
        {
            stakeholderId: 15,
            message: 'Review pending: Trial balance awaiting your approval',
            type: 'approval_request',
            readStatus: false,
            sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 5,
            relatedReportId: 7,
        },
        {
            stakeholderId: 17,
            message: 'Action required: Global Manufacturing Ltd trial report needs approval',
            type: 'approval_request',
            readStatus: false,
            sentAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 3,
            relatedReportId: 11,
        },
        // Approval requests - Read
        {
            stakeholderId: 14,
            message: 'Approval needed: Trial report for Financial Group LLC - December 2023',
            type: 'approval_request',
            readStatus: true,
            sentAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 4,
            relatedReportId: 14,
        },
        {
            stakeholderId: 16,
            message: 'Review pending: Trial balance awaiting your approval',
            type: 'approval_request',
            readStatus: true,
            sentAt: new Date(Date.now() - 17 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 6,
            relatedReportId: 17,
        },
        {
            stakeholderId: 18,
            message: 'Action required: Healthcare Services Co trial report needs approval',
            type: 'approval_request',
            readStatus: true,
            sentAt: new Date(Date.now() - 19 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 8,
            relatedReportId: 21,
        },
        {
            stakeholderId: 13,
            message: 'Approval needed: Trial report for Energy Solutions Ltd - Q4 2023',
            type: 'approval_request',
            readStatus: true,
            sentAt: new Date(Date.now() - 24 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 9,
            relatedReportId: 25,
        },
        {
            stakeholderId: 15,
            message: 'Review pending: Trial balance awaiting your approval',
            type: 'approval_request',
            readStatus: true,
            sentAt: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            relatedEntityId: 10,
            relatedReportId: 29,
        },
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});