import { db } from '@/db';
import { trialReports } from '@/db/schema';

async function main() {
    const reportingPeriods = [
        '2024-01-31',
        '2024-02-29',
        '2024-03-31',
        '2024-04-30',
        '2024-05-31',
        '2024-06-30'
    ];

    const sampleTrialReports = [
        // Entity 1 - 3 reports
        {
            entityId: 1,
            reportingPeriod: '2024-01-31',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 4500000,
            totalCredits: 4500000,
            balanceDifference: 0,
            uploadedBy: 3,
            uploadedAt: new Date('2024-02-05').toISOString(),
            reviewedBy: 11,
            reviewedAt: new Date('2024-02-08').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-1-2024-01-31.xlsx',
        },
        {
            entityId: 1,
            reportingPeriod: '2024-03-31',
            reportType: 'quarterly',
            status: 'approved',
            totalDebits: 8750000,
            totalCredits: 8750000,
            balanceDifference: 0,
            uploadedBy: 3,
            uploadedAt: new Date('2024-04-03').toISOString(),
            reviewedBy: 9,
            reviewedAt: new Date('2024-04-07').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-1-2024-03-31.xlsx',
        },
        {
            entityId: 1,
            reportingPeriod: '2024-05-31',
            reportType: 'monthly',
            status: 'in_review',
            totalDebits: 5200000,
            totalCredits: 5195000,
            balanceDifference: 5000,
            uploadedBy: 3,
            uploadedAt: new Date('2024-06-02').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-1-2024-05-31.xlsx',
        },
        // Entity 2 - 3 reports
        {
            entityId: 2,
            reportingPeriod: '2024-02-29',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 3200000,
            totalCredits: 3200000,
            balanceDifference: 0,
            uploadedBy: 2,
            uploadedAt: new Date('2024-03-04').toISOString(),
            reviewedBy: 10,
            reviewedAt: new Date('2024-03-09').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-2-2024-02-29.xlsx',
        },
        {
            entityId: 2,
            reportingPeriod: '2024-04-30',
            reportType: 'monthly',
            status: 'pending',
            totalDebits: 3850000,
            totalCredits: 3842000,
            balanceDifference: 8000,
            uploadedBy: 2,
            uploadedAt: new Date('2024-05-03').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-2-2024-04-30.xlsx',
        },
        {
            entityId: 2,
            reportingPeriod: '2024-06-30',
            reportType: 'quarterly',
            status: 'rejected',
            totalDebits: 7500000,
            totalCredits: 7455000,
            balanceDifference: 45000,
            uploadedBy: 2,
            uploadedAt: new Date('2024-07-02').toISOString(),
            reviewedBy: 12,
            reviewedAt: new Date('2024-07-06').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-2-2024-06-30.xlsx',
        },
        // Entity 3 - 3 reports
        {
            entityId: 3,
            reportingPeriod: '2024-01-31',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 6800000,
            totalCredits: 6800000,
            balanceDifference: 0,
            uploadedBy: 5,
            uploadedAt: new Date('2024-02-06').toISOString(),
            reviewedBy: 13,
            reviewedAt: new Date('2024-02-10').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-3-2024-01-31.xlsx',
        },
        {
            entityId: 3,
            reportingPeriod: '2024-03-31',
            reportType: 'quarterly',
            status: 'approved',
            totalDebits: 9500000,
            totalCredits: 9500000,
            balanceDifference: 0,
            uploadedBy: 5,
            uploadedAt: new Date('2024-04-04').toISOString(),
            reviewedBy: 14,
            reviewedAt: new Date('2024-04-08').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-3-2024-03-31.xlsx',
        },
        {
            entityId: 3,
            reportingPeriod: '2024-05-31',
            reportType: 'monthly',
            status: 'in_review',
            totalDebits: 7100000,
            totalCredits: 7093000,
            balanceDifference: 7000,
            uploadedBy: 5,
            uploadedAt: new Date('2024-06-04').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-3-2024-05-31.xlsx',
        },
        // Entity 4 - 3 reports
        {
            entityId: 4,
            reportingPeriod: '2024-02-29',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 2800000,
            totalCredits: 2800000,
            balanceDifference: 0,
            uploadedBy: 1,
            uploadedAt: new Date('2024-03-05').toISOString(),
            reviewedBy: 11,
            reviewedAt: new Date('2024-03-10').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-4-2024-02-29.xlsx',
        },
        {
            entityId: 4,
            reportingPeriod: '2024-04-30',
            reportType: 'monthly',
            status: 'pending',
            totalDebits: 3100000,
            totalCredits: 3106000,
            balanceDifference: -6000,
            uploadedBy: 1,
            uploadedAt: new Date('2024-05-05').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-4-2024-04-30.xlsx',
        },
        {
            entityId: 4,
            reportingPeriod: '2024-06-30',
            reportType: 'quarterly',
            status: 'in_review',
            totalDebits: 6200000,
            totalCredits: 6192000,
            balanceDifference: 8000,
            uploadedBy: 1,
            uploadedAt: new Date('2024-07-03').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-4-2024-06-30.xlsx',
        },
        // Entity 5 - 3 reports
        {
            entityId: 5,
            reportingPeriod: '2024-01-31',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 5500000,
            totalCredits: 5500000,
            balanceDifference: 0,
            uploadedBy: 4,
            uploadedAt: new Date('2024-02-07').toISOString(),
            reviewedBy: 9,
            reviewedAt: new Date('2024-02-11').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-5-2024-01-31.xlsx',
        },
        {
            entityId: 5,
            reportingPeriod: '2024-03-31',
            reportType: 'quarterly',
            status: 'rejected',
            totalDebits: 8900000,
            totalCredits: 8852000,
            balanceDifference: 48000,
            uploadedBy: 4,
            uploadedAt: new Date('2024-04-05').toISOString(),
            reviewedBy: 10,
            reviewedAt: new Date('2024-04-09').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-5-2024-03-31.xlsx',
        },
        {
            entityId: 5,
            reportingPeriod: '2024-05-31',
            reportType: 'monthly',
            status: 'pending',
            totalDebits: 5900000,
            totalCredits: 5891000,
            balanceDifference: 9000,
            uploadedBy: 4,
            uploadedAt: new Date('2024-06-05').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-5-2024-05-31.xlsx',
        },
        // Entity 6 - 3 reports
        {
            entityId: 6,
            reportingPeriod: '2024-02-29',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 4100000,
            totalCredits: 4100000,
            balanceDifference: 0,
            uploadedBy: 6,
            uploadedAt: new Date('2024-03-06').toISOString(),
            reviewedBy: 12,
            reviewedAt: new Date('2024-03-11').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-6-2024-02-29.xlsx',
        },
        {
            entityId: 6,
            reportingPeriod: '2024-04-30',
            reportType: 'monthly',
            status: 'in_review',
            totalDebits: 4300000,
            totalCredits: 4308000,
            balanceDifference: -8000,
            uploadedBy: 6,
            uploadedAt: new Date('2024-05-06').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-6-2024-04-30.xlsx',
        },
        {
            entityId: 6,
            reportingPeriod: '2024-06-30',
            reportType: 'quarterly',
            status: 'approved',
            totalDebits: 7800000,
            totalCredits: 7800000,
            balanceDifference: 0,
            uploadedBy: 6,
            uploadedAt: new Date('2024-07-04').toISOString(),
            reviewedBy: 13,
            reviewedAt: new Date('2024-07-08').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-6-2024-06-30.xlsx',
        },
        // Entity 7 - 3 reports
        {
            entityId: 7,
            reportingPeriod: '2024-01-31',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 3600000,
            totalCredits: 3600000,
            balanceDifference: 0,
            uploadedBy: 7,
            uploadedAt: new Date('2024-02-08').toISOString(),
            reviewedBy: 14,
            reviewedAt: new Date('2024-02-12').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-7-2024-01-31.xlsx',
        },
        {
            entityId: 7,
            reportingPeriod: '2024-03-31',
            reportType: 'quarterly',
            status: 'in_review',
            totalDebits: 7200000,
            totalCredits: 7196000,
            balanceDifference: 4000,
            uploadedBy: 7,
            uploadedAt: new Date('2024-04-06').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-7-2024-03-31.xlsx',
        },
        {
            entityId: 7,
            reportingPeriod: '2024-05-31',
            reportType: 'monthly',
            status: 'pending',
            totalDebits: 3900000,
            totalCredits: 3895000,
            balanceDifference: 5000,
            uploadedBy: 7,
            uploadedAt: new Date('2024-06-06').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-7-2024-05-31.xlsx',
        },
        // Entity 8 - 3 reports
        {
            entityId: 8,
            reportingPeriod: '2024-02-29',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 10000000,
            totalCredits: 10000000,
            balanceDifference: 0,
            uploadedBy: 8,
            uploadedAt: new Date('2024-03-07').toISOString(),
            reviewedBy: 11,
            reviewedAt: new Date('2024-03-12').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-8-2024-02-29.xlsx',
        },
        {
            entityId: 8,
            reportingPeriod: '2024-04-30',
            reportType: 'monthly',
            status: 'in_review',
            totalDebits: 9800000,
            totalCredits: 9794000,
            balanceDifference: 6000,
            uploadedBy: 8,
            uploadedAt: new Date('2024-05-07').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-8-2024-04-30.xlsx',
        },
        {
            entityId: 8,
            reportingPeriod: '2024-06-30',
            reportType: 'yearly',
            status: 'pending',
            totalDebits: 15500000,
            totalCredits: 15510000,
            balanceDifference: -10000,
            uploadedBy: 8,
            uploadedAt: new Date('2024-07-05').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-8-2024-06-30.xlsx',
        },
        // Entity 9 - 3 reports
        {
            entityId: 9,
            reportingPeriod: '2024-01-31',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 2500000,
            totalCredits: 2500000,
            balanceDifference: 0,
            uploadedBy: 2,
            uploadedAt: new Date('2024-02-09').toISOString(),
            reviewedBy: 9,
            reviewedAt: new Date('2024-02-13').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-9-2024-01-31.xlsx',
        },
        {
            entityId: 9,
            reportingPeriod: '2024-03-31',
            reportType: 'quarterly',
            status: 'rejected',
            totalDebits: 5100000,
            totalCredits: 5150000,
            balanceDifference: -50000,
            uploadedBy: 2,
            uploadedAt: new Date('2024-04-07').toISOString(),
            reviewedBy: 10,
            reviewedAt: new Date('2024-04-11').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-9-2024-03-31.xlsx',
        },
        {
            entityId: 9,
            reportingPeriod: '2024-05-31',
            reportType: 'monthly',
            status: 'pending',
            totalDebits: 2700000,
            totalCredits: 2702000,
            balanceDifference: -2000,
            uploadedBy: 2,
            uploadedAt: new Date('2024-06-07').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-9-2024-05-31.xlsx',
        },
        // Entity 10 - 3 reports
        {
            entityId: 10,
            reportingPeriod: '2024-02-29',
            reportType: 'monthly',
            status: 'approved',
            totalDebits: 8200000,
            totalCredits: 8200000,
            balanceDifference: 0,
            uploadedBy: 5,
            uploadedAt: new Date('2024-03-08').toISOString(),
            reviewedBy: 12,
            reviewedAt: new Date('2024-03-13').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-10-2024-02-29.xlsx',
        },
        {
            entityId: 10,
            reportingPeriod: '2024-04-30',
            reportType: 'yearly',
            status: 'in_review',
            totalDebits: 18000000,
            totalCredits: 17998000,
            balanceDifference: 2000,
            uploadedBy: 5,
            uploadedAt: new Date('2024-05-08').toISOString(),
            reviewedBy: null,
            reviewedAt: null,
            fileUrl: '/uploads/trial-reports/entity-10-2024-04-30.xlsx',
        },
        {
            entityId: 10,
            reportingPeriod: '2024-06-30',
            reportType: 'yearly',
            status: 'approved',
            totalDebits: 19500000,
            totalCredits: 19500000,
            balanceDifference: 0,
            uploadedBy: 5,
            uploadedAt: new Date('2024-07-06').toISOString(),
            reviewedBy: 13,
            reviewedAt: new Date('2024-07-10').toISOString(),
            fileUrl: '/uploads/trial-reports/entity-10-2024-06-30.xlsx',
        },
    ];

    await db.insert(trialReports).values(sampleTrialReports);
    
    console.log('✅ Trial reports seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});