import { db } from '@/db';
import { varianceAnalysis } from '@/db/schema';

async function main() {
    const sampleVarianceAnalysis = [
        // Trial Report 1 - MoM variances
        {
            trialReportId: 1,
            glAccountId: 1,
            varianceAmount: 125000.00,
            variancePercentage: 8.5,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-15T10:30:00').toISOString(),
        },
        {
            trialReportId: 1,
            glAccountId: 2,
            varianceAmount: -75000.00,
            variancePercentage: -5.2,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-15T10:31:00').toISOString(),
        },
        {
            trialReportId: 1,
            glAccountId: 3,
            varianceAmount: 450000.00,
            variancePercentage: 35.8,
            periodComparison: 'MoM',
            anomalyDetected: true,
            anomalyReason: 'Unusual spike in expenses compared to previous period',
            createdAt: new Date('2024-01-15T10:32:00').toISOString(),
        },
        {
            trialReportId: 1,
            glAccountId: 4,
            varianceAmount: 88000.00,
            variancePercentage: 12.3,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-15T10:33:00').toISOString(),
        },
        {
            trialReportId: 1,
            glAccountId: 5,
            varianceAmount: -45000.00,
            variancePercentage: -8.9,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-15T10:34:00').toISOString(),
        },

        // Trial Report 2 - QoQ variances
        {
            trialReportId: 2,
            glAccountId: 6,
            varianceAmount: -320000.00,
            variancePercentage: -42.5,
            periodComparison: 'QoQ',
            anomalyDetected: true,
            anomalyReason: 'Significant revenue drop requiring investigation',
            createdAt: new Date('2024-01-16T09:15:00').toISOString(),
        },
        {
            trialReportId: 2,
            glAccountId: 7,
            varianceAmount: 95000.00,
            variancePercentage: 15.7,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-16T09:16:00').toISOString(),
        },
        {
            trialReportId: 2,
            glAccountId: 8,
            varianceAmount: 180000.00,
            variancePercentage: 22.4,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-16T09:17:00').toISOString(),
        },
        {
            trialReportId: 2,
            glAccountId: 9,
            varianceAmount: -65000.00,
            variancePercentage: -10.8,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-16T09:18:00').toISOString(),
        },
        {
            trialReportId: 2,
            glAccountId: 10,
            varianceAmount: 420000.00,
            variancePercentage: 38.2,
            periodComparison: 'QoQ',
            anomalyDetected: true,
            anomalyReason: 'Quarterly seasonal adjustment outside normal range',
            createdAt: new Date('2024-01-16T09:19:00').toISOString(),
        },

        // Trial Report 3 - MoM variances
        {
            trialReportId: 3,
            glAccountId: 11,
            varianceAmount: 155000.00,
            variancePercentage: 18.9,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-17T14:20:00').toISOString(),
        },
        {
            trialReportId: 3,
            glAccountId: 12,
            varianceAmount: -98000.00,
            variancePercentage: -14.2,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-17T14:21:00').toISOString(),
        },
        {
            trialReportId: 3,
            glAccountId: 13,
            varianceAmount: 275000.00,
            variancePercentage: 28.5,
            periodComparison: 'MoM',
            anomalyDetected: true,
            anomalyReason: 'Large one-time transaction detected',
            createdAt: new Date('2024-01-17T14:22:00').toISOString(),
        },
        {
            trialReportId: 3,
            glAccountId: 14,
            varianceAmount: 52000.00,
            variancePercentage: 7.8,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-17T14:23:00').toISOString(),
        },
        {
            trialReportId: 3,
            glAccountId: 15,
            varianceAmount: -120000.00,
            variancePercentage: -16.4,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-17T14:24:00').toISOString(),
        },

        // Trial Report 4 - YoY variances
        {
            trialReportId: 4,
            glAccountId: 16,
            varianceAmount: 380000.00,
            variancePercentage: 31.2,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-18T11:00:00').toISOString(),
        },
        {
            trialReportId: 4,
            glAccountId: 17,
            varianceAmount: -485000.00,
            variancePercentage: -48.5,
            periodComparison: 'YoY',
            anomalyDetected: true,
            anomalyReason: 'Unexplained variance in asset valuation',
            createdAt: new Date('2024-01-18T11:01:00').toISOString(),
        },
        {
            trialReportId: 4,
            glAccountId: 18,
            varianceAmount: 225000.00,
            variancePercentage: 24.7,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-18T11:02:00').toISOString(),
        },
        {
            trialReportId: 4,
            glAccountId: 19,
            varianceAmount: 145000.00,
            variancePercentage: 19.3,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-18T11:03:00').toISOString(),
        },
        {
            trialReportId: 4,
            glAccountId: 20,
            varianceAmount: -280000.00,
            variancePercentage: -32.8,
            periodComparison: 'YoY',
            anomalyDetected: true,
            anomalyReason: 'Year-end adjustment exceeds threshold',
            createdAt: new Date('2024-01-18T11:04:00').toISOString(),
        },

        // Trial Report 5 - MoM variances
        {
            trialReportId: 5,
            glAccountId: 21,
            varianceAmount: 68000.00,
            variancePercentage: 9.2,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-19T15:30:00').toISOString(),
        },
        {
            trialReportId: 5,
            glAccountId: 22,
            varianceAmount: 195000.00,
            variancePercentage: 25.8,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-19T15:31:00').toISOString(),
        },
        {
            trialReportId: 5,
            glAccountId: 23,
            varianceAmount: -355000.00,
            variancePercentage: -41.2,
            periodComparison: 'MoM',
            anomalyDetected: true,
            anomalyReason: 'Account balance trend reversal detected',
            createdAt: new Date('2024-01-19T15:32:00').toISOString(),
        },
        {
            trialReportId: 5,
            glAccountId: 24,
            varianceAmount: 112000.00,
            variancePercentage: 14.6,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-19T15:33:00').toISOString(),
        },
        {
            trialReportId: 5,
            glAccountId: 25,
            varianceAmount: -78000.00,
            variancePercentage: -11.5,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-19T15:34:00').toISOString(),
        },

        // Trial Report 6 - QoQ variances
        {
            trialReportId: 6,
            glAccountId: 26,
            varianceAmount: 265000.00,
            variancePercentage: 27.3,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-20T10:45:00').toISOString(),
        },
        {
            trialReportId: 6,
            glAccountId: 27,
            varianceAmount: -145000.00,
            variancePercentage: -18.7,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-20T10:46:00').toISOString(),
        },
        {
            trialReportId: 6,
            glAccountId: 28,
            varianceAmount: 425000.00,
            variancePercentage: 39.8,
            periodComparison: 'QoQ',
            anomalyDetected: true,
            anomalyReason: 'Multiple large transactions in single period',
            createdAt: new Date('2024-01-20T10:47:00').toISOString(),
        },
        {
            trialReportId: 6,
            glAccountId: 29,
            varianceAmount: 88000.00,
            variancePercentage: 11.9,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-20T10:48:00').toISOString(),
        },
        {
            trialReportId: 6,
            glAccountId: 30,
            varianceAmount: 175000.00,
            variancePercentage: 21.4,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-20T10:49:00').toISOString(),
        },

        // Trial Report 7 - MoM variances
        {
            trialReportId: 7,
            glAccountId: 31,
            varianceAmount: -95000.00,
            variancePercentage: -13.2,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-21T13:15:00').toISOString(),
        },
        {
            trialReportId: 7,
            glAccountId: 32,
            varianceAmount: 320000.00,
            variancePercentage: 29.8,
            periodComparison: 'MoM',
            anomalyDetected: true,
            anomalyReason: 'Unusual spike in expenses compared to previous period',
            createdAt: new Date('2024-01-21T13:16:00').toISOString(),
        },
        {
            trialReportId: 7,
            glAccountId: 33,
            varianceAmount: 135000.00,
            variancePercentage: 17.2,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-21T13:17:00').toISOString(),
        },
        {
            trialReportId: 7,
            glAccountId: 34,
            varianceAmount: -185000.00,
            variancePercentage: -22.6,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-21T13:18:00').toISOString(),
        },
        {
            trialReportId: 7,
            glAccountId: 35,
            varianceAmount: 95000.00,
            variancePercentage: 12.8,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-21T13:19:00').toISOString(),
        },

        // Trial Report 8 - YoY variances
        {
            trialReportId: 8,
            glAccountId: 36,
            varianceAmount: 445000.00,
            variancePercentage: 36.2,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-22T09:30:00').toISOString(),
        },
        {
            trialReportId: 8,
            glAccountId: 37,
            varianceAmount: -265000.00,
            variancePercentage: -28.5,
            periodComparison: 'YoY',
            anomalyDetected: true,
            anomalyReason: 'Significant revenue drop requiring investigation',
            createdAt: new Date('2024-01-22T09:31:00').toISOString(),
        },
        {
            trialReportId: 8,
            glAccountId: 38,
            varianceAmount: 195000.00,
            variancePercentage: 23.8,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-22T09:32:00').toISOString(),
        },
        {
            trialReportId: 8,
            glAccountId: 39,
            varianceAmount: 305000.00,
            variancePercentage: 31.7,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-22T09:33:00').toISOString(),
        },
        {
            trialReportId: 8,
            glAccountId: 40,
            varianceAmount: -125000.00,
            variancePercentage: -15.8,
            periodComparison: 'YoY',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-22T09:34:00').toISOString(),
        },

        // Trial Report 9 - QoQ variances
        {
            trialReportId: 9,
            glAccountId: 41,
            varianceAmount: 215000.00,
            variancePercentage: 26.4,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-23T14:00:00').toISOString(),
        },
        {
            trialReportId: 9,
            glAccountId: 42,
            varianceAmount: -395000.00,
            variancePercentage: -44.2,
            periodComparison: 'QoQ',
            anomalyDetected: true,
            anomalyReason: 'Unexplained variance in asset valuation',
            createdAt: new Date('2024-01-23T14:01:00').toISOString(),
        },
        {
            trialReportId: 9,
            glAccountId: 43,
            varianceAmount: 165000.00,
            variancePercentage: 19.8,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-23T14:02:00').toISOString(),
        },
        {
            trialReportId: 9,
            glAccountId: 44,
            varianceAmount: 285000.00,
            variancePercentage: 28.9,
            periodComparison: 'QoQ',
            anomalyDetected: true,
            anomalyReason: 'Large one-time transaction detected',
            createdAt: new Date('2024-01-23T14:03:00').toISOString(),
        },
        {
            trialReportId: 9,
            glAccountId: 45,
            varianceAmount: -155000.00,
            variancePercentage: -18.2,
            periodComparison: 'QoQ',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-23T14:04:00').toISOString(),
        },

        // Trial Report 10 - MoM variances
        {
            trialReportId: 10,
            glAccountId: 46,
            varianceAmount: 125000.00,
            variancePercentage: 16.5,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-24T11:20:00').toISOString(),
        },
        {
            trialReportId: 10,
            glAccountId: 47,
            varianceAmount: -235000.00,
            variancePercentage: -27.3,
            periodComparison: 'MoM',
            anomalyDetected: true,
            anomalyReason: 'Account balance trend reversal detected',
            createdAt: new Date('2024-01-24T11:21:00').toISOString(),
        },
        {
            trialReportId: 10,
            glAccountId: 48,
            varianceAmount: 365000.00,
            variancePercentage: 33.8,
            periodComparison: 'MoM',
            anomalyDetected: true,
            anomalyReason: 'Multiple large transactions in single period',
            createdAt: new Date('2024-01-24T11:22:00').toISOString(),
        },
        {
            trialReportId: 10,
            glAccountId: 49,
            varianceAmount: 75000.00,
            variancePercentage: 10.2,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-24T11:23:00').toISOString(),
        },
        {
            trialReportId: 10,
            glAccountId: 50,
            varianceAmount: 185000.00,
            variancePercentage: 22.7,
            periodComparison: 'MoM',
            anomalyDetected: false,
            anomalyReason: null,
            createdAt: new Date('2024-01-24T11:24:00').toISOString(),
        },
    ];

    await db.insert(varianceAnalysis).values(sampleVarianceAnalysis);
    
    console.log('✅ Variance Analysis seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});